### ISSUE TITLE
Are there other APIs necessary to define any other driver's API?

### ISSUE THREAD

**Issue by hpoit** [mongodb-labs/mongorover#16]
Hi Chris and Jesse, 

Thanks for the awesome work you guys put up here. 

I'm a novice... Are there any other APIs beside the CRUD for whose specs I would have to build in the case of a Julia wrapper? 

Thanks! Best, Kevin

**Comment by tenthdimension** [comment]
Hey Chris and Jesse, 

Does this answer the question? 

These new MongoDB drivers conform to published specifications.

1. Server Selection - Deciding which server to send database operations to in a MongoDB deployment.

2. Server Discovery and Monitoring - All the logic required to make a MongoDB application highly available.

3. CRUD API - The API for how we Create, Read, Update and Delete data from MongoDB.

4. Authentication - The rules for how to authenticate to MongoDB servers.

https://www.mongodb.com/blog/post/announcing-next-generation-drivers-mongodb

So 1 and 2 are complete, and 3 partially, with 4 left to do? Thanks!

**Comment by ajdavis** [comment]
A driver that wraps the C Driver 1.2 gets 1, 2, and 4 for free. Your user
gives you a "mongodb://" URI that expresses all the options for connecting
to the server or servers, and the C driver does the rest including
authentication. You just need to implement #3 in terms of the C Driver's
mongoc_bulk_operation_t. See the mongorover code for guidance.

**Comment by tenthdimension** [comment]
Thank you

**Comment by tenthdimension** [comment]
Hi Jesse. So is this the only script I need to wrap? https://github.com/mongodb/mongo-c-driver/blob/master/src/mongoc/mongoc-bulk-operation.c

**Comment by christopherjwang** [comment]
Kevin:
This is what the PHP (another driver that wraps the C driver) does. It was recommended to me to do the same. I wouldn't necessarily say that it is the *only* implementation you need to wrap, but I would bet it would be used in the majority of your use cases.

**Comment by tenthdimension** [comment]
Hi @christopherjwang! Thanks for the advice.
