### ISSUE TITLE
ObjectId not a global variable

### ISSUE THREAD

**Issue by dereckmartin** [mongodb-labs/mongorover#23]
I am using mongorover with Lapis Framework.  I am trying to track down an issue, but I can't tell if it is with Lapis or mongorover. 

When I have Lapis in develoment mode (code_cache = "off"), mongorover runs fine.  However, when I run Lapis in production mode with code_cache = "on", I get 1 or 2 calls to mongodb before it stops working completely until lapis is restarted again.

I do get a stack trace from lapis/mongorover with a mongorover specific error message of "ObjectId not a global variable"

```
...
/usr/local/share/lua/5.1/lapis/application.lua:659: ./app.lua:92: ObjectId not a global variable
stack traceback:
        [C]: in function find_one;
        ./app.lua:92: in function: ./app.lua:59 Traceback
...
```

Could you describe under what conditions that message gets returned?

**Comment by ajdavis** [comment]
The error is from here:

https://github.com/mongodb-labs/mongorover/blob/af406a985076d6fc8e9087dc307fa8884a387b60/c_wrapper/lua-object-generators.c#L36

I'm not at all familiar with Lapis and how its code cache works, however. @christopherjwang or @hawka do you know why mongorover's `lua_getglobal(L, "ObjectId")` call might fail in this scenario?

**Comment by christopherjwang** [comment]
I'm not familiar with Lapis either. However, from a brief search on it, having the cache off forces mongorover to be loaded each time (which will instantiate the ObjectID global every time). When turning it off, it will somehow be cleaned such that this error actually occurs. I'll look into it.

I've been slowly un-populating the global space such that ObjectID, BSONNull, and other things are not global variables. That would fix this but requires a bit more development work on my part. Let me re-update this weekend.

**Comment by ajdavis** [comment]
Thanks Christopher!

**Comment by dereckmartin** [comment]
@christopherjwang It is no problem.  I'm glad I could offer something of interest to investigate.  You are probably right about it being in the Global namespace.  Lapis is just a wrapper framework around openresty and the ngx_lua module, and they frown on globals.  After further reading, globals do not persist between requests when using ngx_lua.  I suspect when code_cache is turned on, the global does not persist in cache, and the cached code tries calling a non-existent global.

I will just run with code_cache = "off" for the time being.  It won't hinder performance for what I am doing at the moment.

**Comment by christopherjwang** [comment]
@dereckmartin pull requests coming in, will update you when they're complete!

**Comment by christopherjwang** [comment]
@dereckmartin should be good to go if you install via github. Have to do a couple more things before putting up an update to luarocks. Let me know if you have any other issues!

**Comment by arthur-s** [comment]
I know the solution, look at https://github.com/openresty/lua-nginx-module/#init_by_lua
in nginx.conf write before `server` directive this:
```
    init_by_lua 'MongoClient = require("mongorover.MongoClient")';
    server {
      ...
   }
```
this works for me when lua_code_cache is on

**Comment by ajdavis** [comment]
Closing this because it sounds like it was resolved, please reopen if there are still issues.
