### ISSUE TITLE
Question: Find documents by objectId

### ISSUE THREAD

**Issue by dereckmartin** [mongodb-labs/mongorover#24]
I am trying to find documents by id. I couldn't find an example in the samples using an id except, in http://api.mongodb.org/lua/current/examples/delete_one.lua.html

```
-- After the insert, there should be two.
local arrayOfDocuments = {{foo = "bar", _id = "manually set _id"}, {foo = "baz"}}
```
I have no problem searching for a specific field like below:

``` 
:find_one({ somefield = "text" })
```
However, finding a document by and objectID appears to return nil. 

```
:find_one({ _id = "560b17a2adccb8347b447717" })
```
How should a query for an objectId be formatted?

**Comment by dereckmartin** [comment]
I have sorted this out.

I was using the key string.  However, the id needs to be 'ObjectId("560b17a2adccb8347b447717")'.  I am pulling this ObjectId as a reference in another collection.  So I just store the whole _id object instead of the string representation it self.

**Comment by ajdavis** [comment]
I'm glad you got it sorted out!
