### ISSUE TITLE
Replica set?

### ISSUE THREAD

**Issue by travisbell** [mongodb-labs/mongorover#33]
Hi guys,

Does this driver support connecting to a replica set?

**Comment by ajdavis** [comment]
Yes; mongorover uses the MongoDB C Driver to connect to MongoDB, and passes the connection string through to the C Driver. See the "Replica Set Example" here:

https://api.mongodb.org/c/current/mongoc_uri_t.html

**Comment by travisbell** [comment]
Beautiful, thanks Jesse.
