### ISSUE TITLE
MongoCollection.lua:75: unknown operator: $or

### ISSUE THREAD

**Issue by TheGeminii** [mongodb-labs/mongorover#38]
Is the $or operator supported? and if so, can you give an example using it? 
The  following query gives me the error from the title:
local query = {startDate = {["$lte"] = workingDate}, ["user._id"] = user._id, {["$or"] = {endDate = {["$gte"] = workingDate}, endDate = null}} }

**Comment by christopherjwang** [comment]
Yes $or is supported. Sorry for a late reply. Lua is kind of weird when you start writing queries with mongo, be sure to write them correctly :). You're issue is embedding your "$or" too deeply in your query. You can clearly see it if you prettify your code:

```
local query = {
	startDate = {
		["$lte"] = workingDate
	},
	["user._id"] = user._id,
	{
		["$or"] = {
			endDate = {
				["$gte"] = workingDate
			},
			endDate = null
		}
	}
}
```
To correct your query the way you wrote it, it would look like this (I ran it with dummy values and it is fine):
```
local query = {
	startDate = {
		["$lte"] = workingDate
	},
	["user._id"] = user._id,
	["$or"] = {
		endDate = {
			["$gte"] = workingDate
		},
		endDate = null
	}
}
```

An example is included below. 
```
local MongoClient = require("mongorover.MongoClient")
local client = MongoClient.new("mongodb://localhost:27017/")
local exampleDatabase = client:getDatabase("exampleDB")
local exampleCollection = exampleDatabase:getCollection("exampleCollection")

-- Drop database to get a clean slate for this example.
exampleCollection:drop()

-- After the insert, there should be three documents.
local arrayOfDocuments = {
	{color = "green", awesome = false},
	{color = "blue", awesome = false},
	{color = "red", awesome = true}
}
exampleCollection:insert_many(arrayOfDocuments)

local blue_or_awesome = {
	["$or"] = {
		{ color = "blue" },
		{ awesome = true}
	}
}

local results = exampleCollection:find(blue_or_awesome)

for result in results do
	print(result.color, result.awesome)
end
```

my output is:
```
red     true
blue    false
```

Let me know if that works for you.
