### ISSUE TITLE
Aggregation example does not work

### ISSUE THREAD

**Issue by yzubkov** [mongodb-labs/mongorover#41]
When running the aggregation example (from the examples folder) I get the following error:

bson_append_array(): invalid array detected. first element of array parameter is not "0".

All other lua examples work just fine. I am using mongoc driver version 1.4.0-dev, which is currently master branch. I have also tried the aggregation example in pure C from [here](http://api.mongodb.com/c/1.2.3/aggregate.html) and it works flawlessly. My guess is that the problem originates in lua_table_to_bson where a lua table is incorrectly converted to BSON.

**Comment by ajdavis** [comment]
Hi, I can't reproduce this. I added some printfs to lua_table_to_bson and it appears to correctly generated indexes 0, 1, .... Have you changed nothing about the aggregation example code or the Lua driver source?

**Comment by yzubkov** [comment]
I have just tried again and it definitely does not work for me. Maybe I can provide more clues. Here is the file that I am executing : [pastebin link](http://pastebin.com/fUwSACbc)
I have lua 5.3 and mongoc 1.4.0-dev. I am also on ARM CPU, if that makes a difference. When I execute the file linked above, I get the following output:

`ubuntu@arm:~/script$ ./mongotest.cgi 
bson_append_array(): invalid array detected. first element of array parameter is not "0".
Total weight of cats	nil`

When I modify the script and test if the records were inserted correctly using `col:find({})` I can see all the records are there just as they were supposed to look. Also, please note that all other examples work perfectly fine. The only one that does not work is aggregation.

In the process of looking into this I realized that the aggregation example from the C driver uses the BCON format to build the pipeline, whereas we are using the BSON. If you can point me to an aggregation example written in C that would use BSON format I can test that and rule out the possibility that there might be a problem with the values that we pass to mongoc_collection_aggregate .

I appreciate your help. Thanks!

**Comment by christopherjwang** [comment]
Hey @yzubkov are you using Lua 5.3? If so, how did you end up installing mongorover? We haven't tested any type of support on 5.3. It's quite a bit different from 5.1 and 5.2.

**Comment by ajdavis** [comment]
OK, interesting. I've just built Lua 5.3 from source on Ubuntu 14.04, along with the latest luarocks, the C Driver 1.3.5, and mongorover from master. Now I see this output:
```
$ lua examples/aggregation.lua
bson_append_array(): invalid array detected. first element of array parameter is not "0".
Total weight of cats	nil
```
A couple questions for investigation:

1. First I had to add the line `local BSONNull = require("mongorover.luaBSONObjects.BSONNull")` to the top of `examples/aggregation.lua`. That's important, right? Is that not required in all versions of Lua?
2. Something changed between Lua 5.2 and 5.3 that breaks how mongorover generates array index keys?
2. Although libbson [prints the warning here](https://github.com/ajdavis/libbson/blob/4efe8e266b6a711125d3ca152e0502811a69be0c/src/bson/bson.c#L736-L736), it doesn't actually do anything when it detects a bad index, it just passes the array through to MongoDB. So what really causes the aggregation to return nil instead of the correct result?

**Comment by christopherjwang** [comment]
1. I didn't update the examples when I made 2b8427521ce3e133f92c360dead23bc57d4cad90

Did you by chance make mongorover with cmake? This error gets thrown correctly for me regarding using lua 5.3 and install via luarocks (here's my console output).

```
christopherjwang @ ~/development/mongodb/mongorover
 [65] → sudo luarocks-5.3 make mongorover-0.1-1.rockspec

Missing dependencies for mongorover:
lua >= 5.1, < 5.3


Error: Could not satisfy dependency: lua >= 5.1, < 5.3
```

I'd be happy to dig in, I just want to make sure we're all on the same page.

**Comment by ajdavis** [comment]
Good point Chris. I had to delete the requirements line to build with luarocks and lua 5.3.

**Comment by christopherjwang** [comment]
@yzubkov  This driver is simple enough that supporting 5.3 could be viable. I'll see what I can do, but I have no promises for you.

Thanks for hopping in @ajdavis !

**Comment by ajdavis** [comment]
@yzubkov could you try the driver from the current master and see if it works for you now?

**Comment by yzubkov** [comment]
Just tested our aggregation example under Lua5.3 and everything works great. Thank you AJ and Chris for getting this issue resolved. You guys rock!
