### ISSUE TITLE
How to do $elemMatch query on mongorover

### ISSUE THREAD

**Issue by priyaradhakrishnan0** [mongodb-labs/mongorover#45]
The collection anchors has the structure
{"anchor":some_anchor , pages ;[ {  "page_freq" : some_number,  "page_id" : some_number }]}

I want to query anchors db for pages with page_id = 321544

In mongo command prompt I give
> db.anchors.find({pages: { $elemMatch :{ "page_id":321544} }})

With the mongorover, the following lua code gives exception

local client = mongorover.MongoClient.new("mongodb://"..dbIP..":"..dbPort)
AnchorDb = client:getDatabase("anchorDB")
anchors = AnchorDb:getCollection("anchors")
local results = anchors:find({pages.page_id = "321544"})

Error is 
 '}' expected near '='

I am not sure how to specify "pages: { $elemMatch :{ "page_id":321544} }}" in mongorover. Please help.

**Comment by christopherjwang** [comment]
> With the mongorover, the following lua code gives exception...

whenever you have weird "keys" in lua, you put it in square brackets.

```
local results = anchors:find({["pages.page_id"] = "321544"})
```

> I am not sure how to specify "pages: { $elemMatch :{ "page_id":321544} }}" in mongorover. Please help.

Try this:

```
local results = anchors:find({pages = {["$elemMatch"] = {page_id = 321544}}})
```

While this isn't necessarily mongorover related, it is an interesting syntax of lua that really only comes out while writing mongodb queries. Let me know if it helps!

**Comment by priyaradhakrishnan0** [comment]
Hi,

Thanks for the prompt reply. It works!!

local results = anchors:find({["pages.page_id"] = 321544})

I have one more request. Can you add an example of

mongorover.MongoDatabase:command (command[, value], options)

in the documentation.

Thanks again,

Priya



On Wed, Jul 13, 2016 at 11:08 PM, Christopher Wang <notifications@github.com

**Comment by christopherjwang** [comment]
@priyaradhakrishnan0 https://github.com/mongodb-labs/mongorover/blob/master/test/TestDatabase.lua#L80

**Comment by priyaradhakrishnan0** [comment]
Thanks a lot.
-priya
