### ISSUE TITLE
Does this support client pool?

### ISSUE THREAD

**Issue by GobYang** [mongodb-labs/mongorover#55]
Excuse me, Does this support client pool?

**Comment by ajdavis** [comment]
No it doesn't. The mongoc_client_pool_t is intended for multithreaded programs; are you using multithreading in Lua?

**Comment by GobYang** [comment]
@ajdavis  Thank you very munch for answer my question.Because my english is not good. I want to describe I wondered thing. 

I use mongorover's api and receive one request insert to mongodb. It's spend about 20 MS. But I use PHP only need about 10 MS.

So I want know mongorover is support connect pool? If every request need to connect mongodb.It's not good.

Do you have any advice?

Thank you very much.

**Comment by ajdavis** [comment]
I see. Do this:
```
client = mongorover.MongoClient.new("mongodb://localhost:27017/")
```
And use the *same* client for all operations. Only call `MongoClient.new` in your application. Then you will connect to MongoDB once, and reuse that connection.
