### ISSUE TITLE
Implement DateTime functionality

### ISSUE THREAD

**Issue by wubin19896817** [mongodb-labs/mongorover#59]

**Comment by christopherjwang** [comment]
Hey there. Great question.

I'm assuming you want to use find with sort.
Since mongorover is a wrapper around the C driver, to use sort with find you need to use the $query syntax. You can find that in the [c documentation](http://mongoc.org/libmongoc/current/mongoc_collection_find.html). I should probably update that in the mongorover documentation, since it isn't very clear and is a bit roundabout to make you look over at the c docs to find that type of information. Here's a script to help you get started.

```
local MongoClient = require("mongorover.MongoClient")
local client = MongoClient.new("mongodb://localhost:27017/")
local exampleDatabase = client:getDatabase("exampleDB")
local exampleCollection = exampleDatabase:getCollection("exampleCollection")

-- I'm only dropping the collection for the sake of this example, so you can run it many times without getting duplicate results
exampleCollection:drop()

local arrayOfDocuments = {{a = 1}, {a = 2}, {a = 3}}
exampleCollection:insert_many(arrayOfDocuments)

for result in exampleCollection:find({['$query'] = {}, ['$orderby'] = {a = 1}}) do print(result.a) end
for result in exampleCollection:find({['$query'] = {}, ['$orderby'] = {a = -1}}) do print(result.a) end
```

My output for this script is:
```
1
2
3
3
2
1
```

Let me know if this helps.

**Comment by wubin19896817** [comment]
ok, thanks  very much..and sort and skip how to use both. Thank you very much..because I have some problem in you project. like how to use bson time.... It throw no use for bson time

**Comment by christopherjwang** [comment]
You want to build from source to use this. If you've downloaded mongorover from luarocks, that doesn't have the skip functionality. You can find out how to build from source in the README.

```
for result in exampleCollection:find({['$query'] = {}, ['$orderby'] = {a = -1}}, {}, {skip = 2}) do print(result.a) end
```

This would just print out:

```
1
```

As for your [error](https://github.com/mongodb-labs/mongorover/blob/master/c_wrapper/lua-bson.c#L707), it isn't supported yet. I can implement it for you in a couple of days. How does that sound?

**Comment by wubin19896817** [comment]
greate, if you have much time

**Comment by wubin19896817** [comment]
thanks very much

**Comment by wubin19896817** [comment]
sorry to disturb you again. how to use like  range_mongo={_id=1,status=1} mix the query...id = 1 mean select this column, 0 mean no select

**Comment by christopherjwang** [comment]
take a look [here](http://api.mongodb.com/lua/current/examples/find.lua.html#).

```
local results = exampleCollection:find({color = "blue"}, {_id = false, color = true})
```

the second argument, `{_id = false, color = true}`, means that I only want the color field back and not the _id.

The line you're looking for is this one. You can find more information about "projection" [here](https://docs.mongodb.com/manual/tutorial/project-fields-from-query-results/).

**Comment by wubin19896817** [comment]
collection:find({['$query']={{username= "miaopai"}},  ['$orderby'] = {_id = 1}})
this one? it donest work.

**Comment by christopherjwang** [comment]
Ah. Break it down.

Your code:
```
collection:find({['$query']={{username= "miaopai"}}, ['$orderby'] = {_id = 1}})
```

Has a bug in the query `{{username= "miaopai"}}`. It should be `{username= "miaopai"}`

Back to your question...

I'm going to break down your line of code (after fixing the query bug):

```
query = {
  ['$query']={
    username= "miaopai"
  },
  ['$orderby'] = {
    _id = 1
  }
}
collection:find(query)
```

So you're sorting by _id from your $orderby statement.

If you want to only get the id back, you want to use the second parameter to `find` to have a filter.

```
query = {
  ['$query']={
    username= "miaopai"
  },
  ['$orderby'] = {
    _id = 1
  }
}
filter = { _id = true }
collection:find(query, filter)
```

Make sense?

**Comment by christopherjwang** [comment]
@wubin19896817 if you are still interested, you can find some functionality [here](https://github.com/mongodb-labs/mongorover/blob/master/test%2FTestCollection.lua#L64). Let me know if it works out for you!

**Comment by wubin19896817** [comment]
hello, can I use in function in you project
like that
{"status":"{\"$in\": [TIMER,PROGRESS,INVALID,FINISHED,FAILED]}

**Comment by christopherjwang** [comment]
see #38

**Comment by wubin19896817** [comment]
thank you。。。only have or not in？

**Comment by christopherjwang** [comment]
I'd take a look [here](https://docs.mongodb.com/manual/reference/operator/query/) first. You can use the same syntax as the example in #38 for the most part.

not in would be `$nin`.

I'm not sure what else you're asking for, unfortunately. Please elaborate on your questions from here on out to get better responses.

**Comment by wubin19896817** [comment]
hello, I have the last question。。。 could I use the objectID function to generate the object id？ I want to find({'rid': ObjectId(rid)}) this

**Comment by christopherjwang** [comment]
Yes!

```
local MongoClient = require("mongorover.MongoClient")
local client = MongoClient.new("mongodb://localhost:27017/")
local exampleDatabase = client:getDatabase("exampleDB")
local exampleCollection = exampleDatabase:getCollection("exampleCollection")

-- Drop database to get a clean slate for this example.
exampleCollection:drop()

-- Insert a document to get back with the automatically generated _id field
exampleCollection:insert_one({foo = "bar"})
local result = exampleCollection:find_one()

local created_object_id = result["_id"]
print("result's ObjectID", created_object_id)

local find_with_id_result = exampleCollection:find_one({["_id"] = created_object_id})

for k,v in pairs(find_with_id_result) do print(k,v) end
```

my output:

```
result's ObjectID	ObjectID("57fb39a19d1fa212304cd491")
_id	ObjectID("57fb39a19d1fa212304cd491")
foo	bar
```

**Comment by wubin19896817** [comment]
I meant if I have  "rid" : ObjectId("578450592b8a68027b8ec65a") 578450592b8a68027b8ec65a. How I change it to ObjectId. How I search the objectId which has the value 578450592b8a68027b8ec65a

**Comment by wubin19896817** [comment]
thanks for your answer.

**Comment by christopherjwang** [comment]
This is how you would make an ObjectId with a string
```
local ObjectId = require("mongorover.luaBSONObjects.ObjectId")
ObjectId.new('578450592b8a68027b8ec65a')
```

**Comment by wubin19896817** [comment]
thank you....you are so kind

**Comment by christopherjwang** [comment]
Of course. Could I ask what you're working on with Lua and MongoDB?

**Comment by wubin19896817** [comment]
our project..Could you add my qq 1508649213.... I will send you
